blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class BlogPost(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    date = models.DateField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=250)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import BlogPost

def all_blogs(request):
    blogPosts = BlogPost.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogPosts':blogPosts})

def detail(request, blog_id):
    blog = get_object_or_404(BlogPost, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project

def index(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/index.html', {'projects':projects})

blog/templates/blog/all_blogs.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>

<h3 class="text-center mb-5">John has written {{ blogPosts.count }} blog{{ blogPosts.count|pluralize }}</h3>

{% for blogPost in blogPosts %}
<div class="row justify-content-center my-3">
  <div class="col-md-10">
    <a href="{% url 'blog:detail' blogPost.id %}">
      <h2>{{ blogPost.title }}</h2>
    </a>
    <h5 class="text-muted">{{ blogPost.date|date:'M d Y'|upper }}</h5>
    <h4>{{ blogPost.content|striptags|truncatechars:100 }}</h4>
  </div>
</div>
{% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends "portfolio/base.html" %}

{% load static %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ blog.title }}</h1>

<h5 class="text-center text-muted mb-5">{{ blog.date|date:'F jS Y' }}</h5>

{{ blog.content|safe }}

{% endblock %}

portfolio/templates/portfolio/base.html
<!doctype html>

<html lang="en">
  <head>
    {% load static %}
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">

    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'portfolio/icon.jpg' %}">

    <title>John Kile</title>
  </head>
  <body>

    <nav id="topNav" class="navbar navbar-expand-md navbar-light">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">
          <img src="{% static 'portfolio/cube.png' %}" width="30" height="30" class="d-inline-block align-top" alt="John's Logo">
          <span>John Kile</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse text-center" id="navbarNav">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% static 'portfolio/resume.pdf' %}">Resume</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://www.facebook.com/downhomewebsolutions/" target="_blank">facebook</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="https://twitter.com/DownHomeWeb" target="_blank">Twitter</a>
            </li>
            <li>
              <a role="button" href="{% url 'blog:all_blogs' %}" class="btn btn-primary">Blog</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
    {% block content %}{% endblock %}
    </div>

    <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/portfolio/index.html
{% extends 'portfolio/base.html' %}

{% block content %}

{% load static %}
<div class="row justify-content-center my-3">
<div class="col-5">
  <img src="{% static 'portfolio/selfie2.jpg' %}" class="img-fluid">
</div>
</div>

<div class="row justify-content-center mb-3">
<div class="col-md-9 text-center">
  <h1 id="hometext" class="font-weight-bold">John Kile is the sole proprietor of Down Home Web Solutions &#128516;</h1>
</div>
</div>

<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
{% for project in projects %}
<div class="col-lg-4 col-md-6">

  {% if project.url %}
  <a href="{{ project.url }}">
    <img src="{{ project.image.url }}" class="img-fluid mb-2">
  </a>
  {% else %}

  <img src="{{ project.image.url }}" class="img-fluid mb-2">
  {% endif %}
  <h3>{{ project.title }}</h3>
  <p>{{ project.description }}</p>
  <br>
  <br>

</div>
{% endfor %}
</div>

{% endblock %}